### ISSUE TITLE
Add "loading spinner" when portfolio is created

### ISSUE THREAD

**Issue by 1l2p** [ml-learning/lemon#3]
Currently, the user does not get any feedback when the portfolio is created. And the creation takes a while. Either add a "spinner" or some other way to give clear feedback.

**Comment by nooralasa** [comment]
I'm assigning this to Su.

Su when you are redesigning the registration page, keep track of the state that the registration page is in (active, waiting, inactive). Inactive means that the button (arrow previously) will be inactive. Waiting means that the link (the green button previously) has been clicked and we are waiting for it to return. Active means that the link returned and that the user should be allowed to proceed.

The spinner should appear in the waiting state. Generally this would be really quick that the user won't notice it, but it is relevant in creating the portfolio since it takes a bit of time.
